name: Build Wheel

on:
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
          
    - name: Install dependencies
      run: |
        sudo apt-get update
        #sudo apt-get upgrade -y
        sudo apt-get install -y opencl-headers clinfo
        sudo apt-get install -y ocl-icd-opencl-dev
        #sudo apt-get install -y intel-opencl-icd intel-compute-runtime
    
    - name: Verify OpenCL installation
      run: clinfo

    - name: Install pytorch
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
        echo "Python3 Path = $(which python3)"
      
    - name: Build
      run: |
        source .venv/bin/activate
        #SITE_PATH=$(find . -name "site-packages" -print -quit 2>/dev/null)
        SITE_PATH=$(python3 -m site)
        echo "SITE_PATH = $SITE_PATH"
        echo "VIRTUAL_ENV = $VIRTUAL_ENV"
        
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=$VIRTUAL_ENV/lib/python3.10/site-packages/torch/share/cmake/Torch -DCMAKE_INSTALL_PREFIX=/usr/local ..
        make
        
    - name: Package build
      run: |
        find . -name "*.whl"
        mkdir artifacts
        cp build/*.whl artifacts/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux build
        path: artifacts/
          
    - name: Test
      run: |
        cd build
        make install
        cd -
        
        export PYTHONPATH=build
        python mnist.py --device
